export { default as Banner } from "./Banner"
export { default as Services } from "./Services"
export { default as Projects } from "./Projects"
export { default as Partners } from "./Partners"
export { default as Customers } from "./Customers"
export { default as About } from "./About"